export const categories = [
    {
        id: '1',
        name: 'Образование',
        // color: '#1142AA',
        color: '#ffa367',
    },
    {
        id: '2',
        name: 'Харинама',
        // color: '#Ffbe40',
        color: '#ffccab',
    },
    {
        id: '3',
        name: 'Мероприятие',
        // color: '#FFB173',
        color: '#ffe0ab',
    },
    {
        id: '4',
        name: 'Киртан',
        // color: '#FF7100',
        color: '#94aed4',
    },
    {
        id: '5',
        name: 'Праздник',
        // color: '#009b95',
        color: '#8cd1c4',
    },
];

export const events = [
    {
        name: 'Курс подготовки к пранама-мантре',
        startDate: '2025-02-06T21:00:00.000Z',
        endDate: '2025-02-07T21:00:00.000Z',
        startTime: '10:00',
        endTime: '18:00',
        place: 'Центр на Нагорной',
        url: 'http://afisha-hk.ru/pranamacourse',
        lent: '',
        categoryId: '1',
    },
    {
        name: 'Маха харинама на День города',
        startDate: '2025-02-07T21:00:00.000Z',
        endDate: '',
        startTime: '12:00',
        endTime: '',
        place: '',
        url: 'http://afisha-hk.ru/mahaharinam2024',
        lent: '',
        categoryId: '2',
    },
    {
        name: 'Радхаштами',
        startDate: '2025-02-10T21:00:00.000Z',
        endDate: '',
        startTime: '13:00',
        endTime: '',
        place: 'Храм Кришны в Москве, Центр на Нагорной',
        url: 'http://afisha-hk.ru/radhashtami2024',
        lent: '',
        categoryId: '3',
    },
    {
        name: 'Бхакти-шастры в Москве',
        startDate: '2025-02-13T21:00:00.000Z',
        endDate: '',
        startTime: '',
        endTime: '',
        place: 'Центр на Нагорной',
        url: 'http://afisha-hk.ru/bhaktishastri',
        lent: '',
        categoryId: '1',
    },
    {
        name: 'Семинар-практикум «Укрепляя связи, которые нас освобождают»',
        startDate: '2025-02-20T21:00:00.000Z',
        endDate: '',
        startTime: '',
        endTime: '',
        place: 'Центр на Нагорной',
        url: 'http://afisha-hk.ru/grihasthaashram',
        lent: '',
        categoryId: '1',
    },
    {
        name: 'Семинар-практикум «Укрепляя связи, которые нас освобождают»',
        startDate: '2025-02-20T21:00:00.000Z',
        endDate: '',
        startTime: '',
        endTime: '',
        place: 'Центр на Нагорной',
        url: 'http://afisha-hk.ru/grihasthaashram',
        lent: '',
        categoryId: '2',
    },
    {
        name: 'Джапа-ретрит «Нама-ништха» для матаджи',
        startDate: '2025-02-24T21:00:00.000Z',
        endDate: '2025-02-28T21:00:00.000Z',
        startTime: '10:00',
        endTime: '18:00',
        place: '',
        url: 'http://afisha-hk.ru/namanishtha',
        lent: '',
        categoryId: '3',
    },
    {
        name: 'Джапа-ретрит «Нама-ништха» для матаджи',
        startDate: '2025-02-24T21:00:00.000Z',
        endDate: '2025-02-28T21:00:00.000Z',
        startTime: '10:00',
        endTime: '18:00',
        place: '',
        url: 'http://afisha-hk.ru/namanishtha',
        lent: '',
        categoryId: '1',
    },
    {
        name: 'Джапа-ретрит «Нама-ништха» для матаджи',
        startDate: '2025-02-24T21:00:00.000Z',
        endDate: '2025-02-28T21:00:00.000Z',
        startTime: '10:00',
        endTime: '18:00',
        place: '',
        url: 'http://afisha-hk.ru/namanishtha',
        lent: '',
        categoryId: '2',
    },
];
